version: '3'

services:
  app:
    image: thusspokedata/kooben-be:latest
    platform: linux/amd64
    restart: always
    container_name: koobenApp-dockereando
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_VERSION: ${APP_VERSION}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      STAGE: ${STAGE}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}

volumes:
  postgres-db:
    external: false
