version: '3.8'

services:
  frontend:
    image: thusspokedata/kooben-fe:latest
    container_name: kooben-frontend
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production 